version = "0.2.1"

formats = ["pdf", "epub"]

[pdf.spine]
title = "Merged Subdir Imports"
vertebrae = ["content/**/*.typ"]
merge = true

[epub.spine]
title = "Merged Subdir Imports"
vertebrae = ["content/**/*.typ"]
